### PR TITLE
Migrate to prop-types package.

### PR DESCRIPTION
**Pull request by bkdev98**
Fix PropTypes deprecated warning of the lastest React version.

### CODE REVIEW

**Comment by AVVS** [comment]
please put prop-types in peer dependencies as well, then we can merge this

**Comment by AVVS** [comment]
```
    Cannot find module 'react-test-renderer/shallow' from 'react-compat.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:151:17)
      at node_modules/enzyme/build/react-compat.js:151:34
      at Object.<anonymous> (node_modules/enzyme/build/react-compat.js:219:5)
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.47s
Ran all test suites.
console.error node_modules/enzyme/build/react-compat.js:158
    react-test-renderer is an implicit dependency in order to support react@15.5+. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation
```

**Comment by bkdev98** [comment]
I have a little confuse about peer dependencies. The instruction of prop-types recommend putting it in _dependencies_ for both apps and librabries (https://www.npmjs.com/package/prop-types). So what does peer dependency do?

**Comment by AVVS** [comment]
peer means it has to be installed on the app level by the end user and is not fetched by the library
even though they recommend that, I don’t see any reason to bundle multiple versions what so ever

**Comment by AVVS** [comment]
Published in 5.1.0

**Comment by paibamboo** [comment]
@AVVS Why do you think this should be peer dependency? I use typescript so I don't PropTypes. But since I upgrade redux-connect from 5.0.0 to 5.1.0, I need to install prop-types as peer dependency although I'm not using it in my project.

**Comment by AVVS** [comment]
prop-types module is used in the production level code and, therefore, it would either go normal deps or dev + peer. I opted in for peer, because it makes the end user aware of this package being required, while not pinning it to specific version
